enum class KeywordEnum() {
    NEW,
    MATERIAL,
    PLANE,
    SPHERE,
    DIFFUSE,
    SPECULAR,
    UNIFORM,
    CHECKERED,
    IMAGE,
    IDENTITY,
    TRANSLATION,
    ROTATION_X,
    ROTATION_Y,
    ROTATION_Z,
    SCALING,
    CAMERA,
    ORTHOGONAL,
    PERSPECTIVE,
    FLOAT
}
val Dict = mapOf("new" to KeywordEnum.NEW, "New" to KeywordEnum.NEW,
                "material" to KeywordEnum.MATERIAL, "Material" to KeywordEnum.MATERIAL,
                "plane" to KeywordEnum.PLANE, "Plane" to KeywordEnum.PLANE,
                "sphere" to KeywordEnum.SPHERE, "Sphere" to KeywordEnum.SPHERE,
                "diffuse" to KeywordEnum.DIFFUSE, "Diffuse" to KeywordEnum.DIFFUSE,
                "specular" to KeywordEnum.SPECULAR, "Specular" to KeywordEnum.SPECULAR,
                "uniform" to KeywordEnum.UNIFORM, "Uniform" to KeywordEnum.UNIFORM,
                "checkered" to KeywordEnum.CHECKERED, "Checkered" to KeywordEnum.CHECKERED,
                "image" to KeywordEnum.IMAGE, "Image" to KeywordEnum.IMAGE,
                "identity" to KeywordEnum.IDENTITY, "Identity" to KeywordEnum.IDENTITY,
                "translation" to KeywordEnum.TRANSLATION, "Translation" to KeywordEnum.TRANSLATION,
                "rotation_x" to KeywordEnum.ROTATION_X, "Rotation_x" to KeywordEnum.ROTATION_X, "rotationX" to KeywordEnum.ROTATION_X, "RotationX" to KeywordEnum.ROTATION_X,
                "rotation_y" to KeywordEnum.ROTATION_Y, "Rotation_y" to KeywordEnum.ROTATION_Y, "rotationY" to KeywordEnum.ROTATION_Y, "RotationY" to KeywordEnum.ROTATION_Y,
                "rotation_z" to KeywordEnum.ROTATION_Z, "Rotation_z" to KeywordEnum.ROTATION_Z, "rotationZ" to KeywordEnum.ROTATION_Z, "RotationZ" to KeywordEnum.ROTATION_Z,
                "scaling" to KeywordEnum.SCALING, "Scaling" to KeywordEnum.SCALING,
                "camera" to KeywordEnum.CAMERA, "Camera" to KeywordEnum.CAMERA,
                "orthogonal" to KeywordEnum.ORTHOGONAL, "Orthogonal" to KeywordEnum.ORTHOGONAL,
                "perspective" to KeywordEnum.PERSPECTIVE, "Perspective" to KeywordEnum.PERSPECTIVE,
                "float" to KeywordEnum.FLOAT, "Float" to KeywordEnum.FLOAT)